### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by onthebigtree** [noahzn/Lite-Mono#2]
When will the training code be released, I am very much looking forward to seeing the specific implementation

**Comment by noahzn** [comment]
Hi, there will still be some time before we release the training code. If you can't wait you can implement it yourself. Our training code is based on monodepth2 [trainer.py](https://github.com/nianticlabs/monodepth2/blob/master/trainer.py), and it is easy to implement since we do not make many modifications. You can refer to the **implementation details** of our paper.

**Comment by noahzn** [comment]
Hi @onthebigtree , the training code has been released.

**Comment by onthebigtree** [comment]
> Hi @onthebigtree , the training code has been released.

Absolutely amazing, thank you for your tireless efforts!
