### ISSUE TITLE
kitti datasets preparation

### ISSUE THREAD

**Issue by sunhucheng** [noahzn/Lite-Mono#41]
Hi~, noahzn
I have some confusion about how to prepare the dataset. What is' eigen 'and' eigen zhou ', do they all need to be included in the split? Can you provide a prepared data compression package? Thank you very much！

**Comment by noahzn** [comment]
Hi!
The "Eigen split" is [from this paper](https://proceedings.neurips.cc/paper_files/paper/2014/hash/7bccfde7714a1ebadf06c5f4cea752c1-Abstract.html). The "Eigen zhou split" is from [this paper](https://openaccess.thecvf.com/content_cvpr_2017/papers/Zhou_Unsupervised_Learning_of_CVPR_2017_paper.pdf), in which static training frames are removed. So, they are all based on the KITTI dataset but the training/validation images are different.

I'm not able to provide the dataset because of the license of KITTI. Please prepare your training and evaluation data according to the README file of [Monodepth2](https://github.com/nianticlabs/monodepth2).

**Comment by sunhucheng** [comment]
Hi,noahzn
I am so sorry for replying you so late. 
I want to know if this data [data format](https://i.postimg.cc/ZKbFS12b/C1-CC2-C77-40-A3-41-DC-AAC2-D71-F4736-CCE1.jpg) is correct.besides, could you export your conda environment to yaml format and share it with me?could you share pretrained encoder and decoder.pth.I am not a smart gay, Iit's a bit of a headache to do this these days.my email is sunhucheng137@gmail.com,thank you very much!

**Comment by noahzn** [comment]
Your directory structure is incorrect.
The pre-trained encoder and decoder can be found in this repo. There are download links in the results table.
I don't have a `yaml` file. You can install CUDA11.0, PyTorch 1.7.1, or CUDA 11.3, PyTorch 1.12.1.

**Comment by sunhucheng** [comment]
Hi!
thank you so much! I want to train lite mono,and there is a lite mono pretrain.pth,is it used for encoder training by --mypretrain?LAST REQUEST:could you provide me a correct kitti directory structure.I am very appreciate for your help!

**Comment by noahzn** [comment]
The `.pth` file you mentioned is the weights pre-trained on ImageNet. You need to load it by setting `--mypretrain`.

My KITTI folder organizes like this.
![image](https://github.com/noahzn/Lite-Mono/assets/8244850/1d302f09-cabc-4d03-9685-e295820f560a)

**Comment by sunhucheng** [comment]
thank you very much!!!!!! I don't have any other question!thank you again!

**Comment by sunhucheng** [comment]
I closed this issue,thanks!

**Comment by sunhucheng** [comment]
I closed this issue,thanks!
