### ISSUE TITLE
How to Evaluate Model Inference Speed

### ISSUE THREAD

**Issue by Zhangc0715** [noahzn/Lite-Mono#55]
Hello, I would like to ask how the index for evaluating Speed in the paper is calculated.
![2023-07-12 18-10-52 的屏幕截图](https://github.com/noahzn/Lite-Mono/assets/134285155/6b72f940-3a48-418b-b739-445bb2919ef3)
I saw this code in the evaluation [code.](https://github.com/noahzn/Lite-Mono/blob/main/evaluate_depth.py#L74) 
` t1= time_sync()
  output = depth_decoder(encoder(input_color))
  t2 = time_sync()`
I don’t know if it is related to the evaluation.Is it possible to use `T2-T1` to calculate the inference speed? Is it by accumulating the calculation results of each time to get the final calculation speed, which is the final result in the paper?

**Comment by noahzn** [comment]
Hi, yes. The code you mentioned was used to evaluate the speed of the model. You will also need to do warm-ups to infer some images, but not to accumulate time. Then you can use `t2-t1` to get the time of inferring a batch. The final result was reported based on the speed of each image. Based on the batchsize you choose, you will get different results. In this repo there is a figure showing a more detailed speed evaluation under different batchsizes.

**Comment by Zhangc0715** [comment]
> 嗨，是的。您提到的代码用于评估模型的速度。您还需要进行热身来推断一些图像，但不要积累时间。然后您可以使用`t2-t1`来获取推断批次的时间。最终结果是根据每张图像的速度报告的。根据您选择的批量大小，您将得到不同的结果。在这个仓库中，有一个图显示了不同批量大小下更详细的速度评估。

I output an inference speed in the form of code`t2-t1`. When I set `batch_size=16`, the terminal will output 44 times. When I set `batch_size=1`, the terminal will output 697 times. Does this mean the output each time represents the time it takes to infer 1 or 16 batch_sizes, but 697 is not 16 times that of 44. Why? Where did the 7 less pictures go?

**Comment by Zhangc0715** [comment]
Another question is, how is the final result obtained? Is it to average these numbers in the terminal, because I found that the speed gap is too large, the slowest speed can reach 26.50ms, and the fastest speed can be It reaches 6.41ms, and the fluctuation range in the middle is also quite large. It is not stable until the last few data. Whether the batch_size is 1 or 16, there will be such a problem. I am not sure whether such data is accurate

**Comment by noahzn** [comment]
Hi, 
1. If you set `batchsize=1` then you get a total time `t` of inferring 697 images. You can compute `t/697` to get an average time for each image. Similarly, if `batchsize=16`, you can accumulate the time 43 times, and then you compute `t/(16*43)`.
2. Since your purpose is to evaluate the speed, it's not really necessary to load the real 697 images. You can simply create, for example, 1000 fake images using `data = torch.rand(1000, 3, 192, 640)`. In this way you can control the number of images to make sure it can be divided by the batchsize.
3. Different batchsizes have different speeds. It also depends a lot on the GPU you are using. 
4. `"It is not stable until the last few data." ` Therefore, it is very important to do **warm-ups** as I told you. You should let the network infer some images (e.g. 100) without accumulating the time.

**Comment by noahzn** [comment]
I am now closing this issue due to no response. You can reopen it or create a new issue if you have further questions.
