### ISSUE TITLE
About the estimated depth distance

### ISSUE THREAD

**Issue by lmj250** [noahzn/Lite-Mono#86]
Hello, author!  I want to know how to get the actual predicted depth value when testing a single image. Whether the 'pred_depth' in the 'evaluate_depth.py'  is the predicted depth value? Here, can I apply the pred_depth calculation in the 'evaluate_depth.py' to 'test_simple.py' to get predicted depth value  in a single image test?

**Comment by noahzn** [comment]
Hi, you cannot get absolute depth values using this method. Please see our discussion [here](https://github.com/noahzn/Lite-Mono/issues/84).

**Comment by lmj250** [comment]
Thank you for replying. In the method, the scaling factor is obtained by combining the ground truth and the predicted depth value. In the subsequent test, the predicted depth value is converted into an absolute depth value by using the scaling factor. However, the corresponding scaling factor cannot be obtained when the image of the non-KITTI dataset is tested. Whether I understood your expression correctly.

**Comment by noahzn** [comment]
Hi, yes, you are correct. The evaluation is based on median scaling. If you don't have the ground-truth, you can not evaluate the accuracy.

**Comment by lmj250** [comment]
I'm still a little confused. If the ground-truth is required to predict the absolute depth distance, how to predict the depth distance in real time and apply it to autonomous driving. I've seen elsewhere that this scaling factor is limited by camera parameters, not sure if that's correct.

**Comment by noahzn** [comment]
“If the ground-truth is required to predict the absolute depth distance”

No, the ground-truth is only needed to evaluate the performance of the model. It's not used to predict the absolute depth distance, because we cannot get a perfect scale factor by using median scaling. 

For self-supervised methods, they are used to predict relative depth, not absolute depth. Therefore, you cannot directly use these methods for absolute depth estimation in autonomous driving. If you want to get rough absolute depth while you don't have any ground-truth. You can try to get a baseline from stereo methods, then you get a factor to scale the predicted depth. Please select the appropriate method according to your application and tolerance for error.

**Comment by noahzn** [comment]
I am closing this issue due to no response.
